// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBH6fOuz-1LDGNZZkhkzx0B8X5-qQHicg',
    appId: '1:562608639503:web:fb6c1ed6383f1789141d7a',
    messagingSenderId: '562608639503',
    projectId: 'corat-441ee',
    authDomain: 'corat-441ee.firebaseapp.com',
    storageBucket: 'corat-441ee.firebasestorage.app',
    measurementId: 'G-25LMZQHX4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm-v2V_u542HJyo0jhZu_bpD3mIeIQJV8',
    appId: '1:562608639503:android:16411981dda59b9c141d7a',
    messagingSenderId: '562608639503',
    projectId: 'corat-441ee',
    storageBucket: 'corat-441ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4VJbqIL1DMfxJ5UJmRVJyKsqwXFUTc98',
    appId: '1:562608639503:ios:0a88b3fd91a1d784141d7a',
    messagingSenderId: '562608639503',
    projectId: 'corat-441ee',
    storageBucket: 'corat-441ee.firebasestorage.app',
    iosBundleId: 'com.example.coratApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4VJbqIL1DMfxJ5UJmRVJyKsqwXFUTc98',
    appId: '1:562608639503:ios:0a88b3fd91a1d784141d7a',
    messagingSenderId: '562608639503',
    projectId: 'corat-441ee',
    storageBucket: 'corat-441ee.firebasestorage.app',
    iosBundleId: 'com.example.coratApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBH6fOuz-1LDGNZZkhkzx0B8X5-qQHicg',
    appId: '1:562608639503:web:d330f41f091e6c89141d7a',
    messagingSenderId: '562608639503',
    projectId: 'corat-441ee',
    authDomain: 'corat-441ee.firebaseapp.com',
    storageBucket: 'corat-441ee.firebasestorage.app',
    measurementId: 'G-8Q2RN7H0XB',
  );

}